export const browserCoreExamples = [
  "anima browser status",
  "anima browser start",
  "anima browser stop",
  "anima browser tabs",
  "anima browser open https://example.com",
  "anima browser focus abcd1234",
  "anima browser close abcd1234",
  "anima browser screenshot",
  "anima browser screenshot --full-page",
  "anima browser screenshot --ref 12",
  "anima browser snapshot",
  "anima browser snapshot --format aria --limit 200",
  "anima browser snapshot --efficient",
  "anima browser snapshot --labels",
];

export const browserActionExamples = [
  "anima browser navigate https://example.com",
  "anima browser resize 1280 720",
  "anima browser click 12 --double",
  'anima browser type 23 "hello" --submit',
  "anima browser press Enter",
  "anima browser hover 44",
  "anima browser drag 10 11",
  "anima browser select 9 OptionA OptionB",
  "anima browser upload /tmp/anima/uploads/file.pdf",
  'anima browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "anima browser dialog --accept",
  'anima browser wait --text "Done"',
  "anima browser evaluate --fn '(el) => el.textContent' --ref 7",
  "anima browser console --level error",
  "anima browser pdf",
];
