#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ANIMA_INSTALL_E2E_IMAGE:-${ANIMABOT_INSTALL_E2E_IMAGE:-anima-install-e2e:local}}"
INSTALL_URL="${ANIMA_INSTALL_URL:-${ANIMABOT_INSTALL_URL:-https://anima.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ANIMA_E2E_MODELS="${ANIMA_E2E_MODELS:-${ANIMABOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e ANIMA_INSTALL_URL="$INSTALL_URL" \
  -e ANIMA_INSTALL_TAG="${ANIMA_INSTALL_TAG:-${ANIMABOT_INSTALL_TAG:-latest}}" \
  -e ANIMA_E2E_MODELS="$ANIMA_E2E_MODELS" \
  -e ANIMA_INSTALL_E2E_PREVIOUS="${ANIMA_INSTALL_E2E_PREVIOUS:-${ANIMABOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e ANIMA_INSTALL_E2E_SKIP_PREVIOUS="${ANIMA_INSTALL_E2E_SKIP_PREVIOUS:-${ANIMABOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
